### ISSUE TITLE
URL for "big" image on wiki is incorrect

### ISSUE THREAD

**Issue by qny31541** [smurf667/treemapmat#2]
"https://raw.githubusercontent.com/smurf667/treemapmat/master/javadoc/screenshots/heaptreemap.png big]"
should be
"https://raw.githubusercontent.com/smurf667/treemapmat/master/javadoc/screenshots/heaptreemap.png"

Nice project, and underlying library: can't wait to try it out on my graphs.

**Comment by smurf667** [comment]
Oops, a left-over from the migration from the Google Code wiki. Thanks! I haven't worked on the MAT plugin in quite a while. Hope you will find it useful, or maybe you can use the underlying library (treemaplib).
